### ISSUE TITLE
Remove colons (:) from folder names

### ISSUE THREAD

**Issue by aditya-2010** [loveBabbar/CodeHelp-DSA-Busted-Series#108]
Bhaiya, folders names mese colons hataa do.. checkout nahi ho raha.

error: invalid path 'Lecture 10: Solving LeetCode Arrays/arrayIntersection.cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by thepranaygupta** [comment]
> Bhaiya, folders names mese colons hataa do.. checkout nahi ho raha.
> 
> error: invalid path 'Lecture 10: Solving LeetCode Arrays/arrayIntersection.cpp' fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'

It's fixed now 👍
