### ISSUE TITLE
Adding Python language

### ISSUE THREAD

**Issue by CRAZy-Monk3Y** [loveBabbar/CodeHelp-DSA-Busted-Series#154]
I wish to contribute DSA using Python Language, So is it possible to contribute here?

**Comment by thepranaygupta** [comment]
> I wish to contribute DSA using Python Language, So is it possible to contribute here?

Yes @CRAZy-Monk3Y you can contribute your python code to this repository, just make sure that you follow the lectures in [DSA Busted Series](https://www.youtube.com/watch?v=WQoB2z67hvY&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA)

**Comment by CRAZy-Monk3Y** [comment]
thanks @thepranaygupta , will do so.
