### ISSUE TITLE
REGARDING CONTRIBUTIONS MADE IN PYTHON

### ISSUE THREAD

**Issue by s-1-n-t-h** [loveBabbar/CodeHelp-DSA-Busted-Series#157]
I justed wanted to know, why where the contributions made for python language of this repository are not getting merged ? Any specific reasons behind that like code quality or something ?  

Please kindly look into PRs 113 and 106 .

Thank you !

**Comment by thepranaygupta** [comment]
> I justed wanted to know, why where the contributions made for python language of this repository are not getting merged ? Any specific reasons behind that like code quality or something ?
> 
> Please kindly look into PRs 113 and 106 .
> 
> Thank you !

All PRs are being reviewed on a first come first serve basis, your PRs will be merged accordingly.
Thank you for your patience.
