### ISSUE TITLE
Can you provide developer access for this repo, I can contribute for python code.

### ISSUE THREAD

**Issue by pratyushkushwah** [loveBabbar/CodeHelp-DSA-Busted-Series#25]
Requesting developer access

**Comment by DeepakKumar-1** [comment]
Hey! @pratyushkushwah 
https://www.dataschool.io/how-to-contribute-on-github/ 
this will help u

**Comment by pratyushkushwah** [comment]
@DeepakKumar-1 Thanks for the help, I am aware of forking and working but thought if I get dev access then it will be easy for me.
