### ISSUE TITLE
driver code missing i.e int main()

### ISSUE THREAD

**Issue by menotnandan** [loveBabbar/CodeHelp-DSA-Busted-Series#359]
can anybody please help me run these programs such as insertion sort,bubble sort....in visual code, as no int main() is written here.

**Comment by Telomelonia** [comment]
@NandanUpadhyay2611 
It's just non-returnable functions... Call them(check the parameters) when you want to sort the vector.
Use this main if you want to use:- 

`int main(){
vector<int> arr = {5, 2, 4, 3, 1};
bubbleSort(arr, arr.size());
for(auto i: arr) cout<<i<<endl;
return 0;
}
`

**Comment by menotnandan** [comment]
thanks it was useful !
